### ISSUE TITLE
Intellij 蹦

### ISSUE THREAD

**Issue by b-y-f** [labuladong/fucking-algorithm#1097]
```
Internal error. Please refer to https://jb.gg/ide/critical-startup-errors

com.intellij.diagnostic.PluginException: Key com.shuzijun.leetcode.plugin.setting.PersistentConfig duplicated; existingAdapter: ServiceAdapter(descriptor=ServiceDescriptor(interface='com.shuzijun.leetcode.plugin.setting.PersistentConfig', serviceImplementation='com.shuzijun.leetcode.plugin.setting.PersistentConfig', testServiceImplementation='null', headlessImplementation='null', overrides=false, configurationSchemaKey='null', preload=FALSE, client=null), pluginDescriptor=PluginDescriptor(name=LeetCode with labuladong, id=leetcode-helper, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/IdeaIC2022.3/plugins/leetcode-helper, version=1.5.4, package=null, isBundled=false)); descriptor: com.shuzijun.leetcode.plugin.setting.PersistentConfig; app: Application  (containerState PRE_INIT) ; current plugin: leetcode-editor
    at com.intellij.serviceContainer.ComponentManagerImpl.registerServices(ComponentManagerImpl.kt:547)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:259)
    at com.intellij.openapi.client.ClientAwareComponentManager.registerComponents(ClientAwareComponentManager.kt:46)
    at com.intellij.idea.ApplicationLoader.doInitApplication(ApplicationLoader.kt:78)
    at com.intellij.idea.ApplicationLoader.access$doInitApplication(ApplicationLoader.kt:1)
    at com.intellij.idea.ApplicationLoader$doInitApplication$1.invokeSuspend(ApplicationLoader.kt)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
    at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
    at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
    at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
    at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
    at com.intellij.idea.ApplicationLoader.initApplication(ApplicationLoader.kt:61)
    at com.p.s.k.p._g.k(_g.java:60)
    at com.p.s.k.p.p6.k(p6.java:113)
    at com.p.s.k.p.pa.p(pa.java:139)
    at com.p.s.k.p.pG.p(pG.java:57)
    at com.intellij.idea.MainImpl.start(MainImpl.kt:13)
    at com.intellij.idea.StartupUtil$startApplication$7.invokeSuspend(StartupUtil.kt:294)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
    at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
    at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
    at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
    at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
    at com.intellij.idea.Main.main(Main.kt:36)

-----
Your JRE: 17.0.5+1-b653.23 aarch64 (JetBrains s.r.o.)
/Applications/IntelliJ IDEA CE.app/Contents/jbr/Contents/Home
```

**Comment by labuladong** [comment]
需要把原版的 leetcode-editor 卸载，否则配置名称会冲突
