### ISSUE TITLE
idea 提示 获取代码失败

### ISSUE THREAD

**Issue by hw-tutu** [labuladong/fucking-algorithm#2335]
**Version:**
What's the plugin version are you using?

 IntelliJ IDEA 2023.2.4  Build #IU-232.10203.10
JDK: 17.0.8.1; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
OS: Windows 11
Plugin to blame: LeetCode with labuladong version: 2.0.2

**Describe the bug**
可正常登录 以及拉取题目列表  但是获取题目具体信息报错
2024-11-26 14:20:55,506 [1030787315] SEVERE - #online.labuladong.leetcode.plugin - 获取代码失败
java.lang.NullPointerException: Cannot invoke "com.alibaba.fastjson.JSONObject.containsKey(Object)" because "slugStatus" is null
	at com.labuladong.leetcode.plugin.utils.MyUtils.containsSolutionBySlug(MyUtils.java:605)
	at com.labuladong.leetcode.plugin.utils.MyUtils.getMyDiv(MyUtils.java:687)
	at com.labuladong.leetcode.plugin.manager.QuestionManager.getContent(QuestionManager.java:281)
	at com.labuladong.leetcode.plugin.manager.QuestionManager.getQuestion(QuestionManager.java:207)
	at com.labuladong.leetcode.plugin.manager.QuestionManager.lambda$getQuestionByTitleSlug$1(QuestionManager.java:345)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.call(ApplicationImpl.java:303)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Screenshots**

**Comment by labuladong** [comment]
这种一般是网络问题，可以重新拉取一下网站数据然后再试？
https://labuladong.online/algo/intro/jetbrains/#%E9%A2%98%E7%9B%AE%E5%88%97%E8%A1%A8%E6%B2%A1%E6%9C%89-%E2%9C%A8-%E6%A0%87%E8%AE%B0
